// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD64tWfnVA-PVIivO25N0A6kKEhP9YJPlo',
    appId: '1:920517839486:web:eddf54320331f5b003262f',
    messagingSenderId: '920517839486',
    projectId: 'book-pool-rs',
    authDomain: 'book-pool-rs.firebaseapp.com',
    storageBucket: 'book-pool-rs.appspot.com',
    measurementId: 'G-SGZM65EMMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg_rGkZxozRAfvBwbUUboqS5RVVSgUuNM',
    appId: '1:920517839486:android:7066cd73a7a131ab03262f',
    messagingSenderId: '920517839486',
    projectId: 'book-pool-rs',
    storageBucket: 'book-pool-rs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMJ9LHadMcGTpunAEogAJLNGS7vqpOibY',
    appId: '1:920517839486:ios:3ce55e806d68988503262f',
    messagingSenderId: '920517839486',
    projectId: 'book-pool-rs',
    storageBucket: 'book-pool-rs.appspot.com',
    iosBundleId: 'com.NerdNest.bookPool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMJ9LHadMcGTpunAEogAJLNGS7vqpOibY',
    appId: '1:920517839486:ios:c4b2d09f24c8b01703262f',
    messagingSenderId: '920517839486',
    projectId: 'book-pool-rs',
    storageBucket: 'book-pool-rs.appspot.com',
    iosBundleId: 'com.NerdNest.bookPool.RunnerTests',
  );
}
